import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import react from "@vitejs/plugin-react";
import { defineConfig, loadEnv, type Plugin } from "vite";
import { fileURLToPath, URL } from "node:url";

function firebaseMessagingSwPlugin(env: Record<string, string>): Plugin {
  const publicDir = resolve(fileURLToPath(new URL(".", import.meta.url)), "public");

  function writeServiceWorker() {
    const apiKey = env.VITE_FIREBASE_API_KEY ?? "";
    if (!apiKey || apiKey.includes("YOUR_") || apiKey.toLowerCase().includes("placeholder")) {
      return;
    }

    const firebaseConfig = {
      apiKey: env.VITE_FIREBASE_API_KEY,
      authDomain: env.VITE_FIREBASE_AUTH_DOMAIN,
      projectId: env.VITE_FIREBASE_PROJECT_ID,
      storageBucket: env.VITE_FIREBASE_STORAGE_BUCKET,
      messagingSenderId: env.VITE_FIREBASE_MESSAGING_SENDER_ID,
      appId: env.VITE_FIREBASE_APP_ID,
    };

    mkdirSync(publicDir, { recursive: true });
    writeFileSync(
      resolve(publicDir, "firebase-messaging-sw.js"),
      `/* Auto-generated by Vite — do not edit manually */
importScripts("https://www.gstatic.com/firebasejs/11.6.0/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/11.6.0/firebase-messaging-compat.js");

firebase.initializeApp(${JSON.stringify(firebaseConfig, null, 2)});

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  const notification = payload.notification ?? {};
  const title = notification.title || "Vaccination Reminder";
  const options = {
    body: notification.body || "",
    icon: "/icon.png",
    data: payload.data,
  };
  self.registration.showNotification(title, options);
});
`,
    );
  }

  return {
    name: "firebase-messaging-sw",
    configureServer() {
      writeServiceWorker();
    },
    buildStart() {
      writeServiceWorker();
    },
  };
}

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), "");

  return {
    plugins: [react(), firebaseMessagingSwPlugin(env)],
    resolve: {
      alias: {
        "@": fileURLToPath(new URL("./src", import.meta.url)),
      },
    },
    server: {
      port: 5173,
      proxy: {
        "/api": {
          target: "http://localhost:3000",
          changeOrigin: true,
        },
        "/ws": {
          target: "ws://localhost:3000",
          ws: true,
        },
      },
    },
  };
});
